# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        article:
            quality: 100
            filters:
                thumbnail:
                    size: [334,420]
                    mode: outbound
        icon:
            quality: 100
            filters:
             thumbail: { size: [50, 50], mode: outbound, allow_updscale: true }

        echelle:
            quality: 85
            filters:
                scale:
                    dim: [250, 250]

        project:
            quality: 85
            filters:
                thumbnail:
                    size: [ 800,450 ]
                    mode: outbound