# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        article:
            quality: 85
            filters:
                thumbnail:
                    size: [400,250]
                    mode: outbound

        echelle:
            quality: 85
            filters:
                scale:
                    dim: [250, 250]

        project:
            quality: 80
            filters:
                upscale:
                    min: [800, 400]
                thumbnail:
                    min: [ 800, 400 ]
                    mode: outbound
                watermark_image:
                    image: ../uploads/site/logo.png
                    size: 0.1
                    position: bottomright